package studentsystem.studentsystem;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;

import studentsystem.studentsystem.Model.Student;
import studentsystem.studentsystem.Repository.StudentRepository;

@DataJpaTest // This annotation is used to test JPA repositories, usually it is like in memory database is used for testing
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY) // this lets replace test database with an in-memory database for testing
class StudentRepositoryTests {

    @Autowired
    private StudentRepository studentRepository; // This is the repository we are testing

    @Test
    void testSaveStudent() { // This test method is used for save student and check if it is saved correctly
        Student student = new Student(null, "John Doe", "Texas"); // create a new student object with null id, name and address
        // id is null because it will be generated by the database when we save the student, 
        
        Student savedStudent = studentRepository.save(student); // save the student to the repository and get the saved student object

        assertNotNull(savedStudent.getId()); // check if the id of the saved student is not null, which means it was generated by the database
        assertEquals("John Doe", savedStudent.getName()); // check if the name of the saved student is "John Doe"
        assertEquals("Texas", savedStudent.getAddress()); // check if the address of the saved student is "Texas"
    }

    @Test
    void testFindAllStudents() { // This test method is used to find all students and check if it returns the correct list of students
        studentRepository.save(new Student(null, "John Doe", "Texas")); // save a new student to the repository
        studentRepository.save(new Student(null, "Jane Smith", "New York")); // save another student to the repository
 
        List<Student> students = studentRepository.findAll(); // find all students from the repository and get the list of students

        assertEquals(2, students.size()); // check if the size of the list of students is 2, as we given 2 students to save 
        assertFalse(students.isEmpty()); // check if the list of students is not empty, which means it has students in it
    }
}
