apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-system
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/student_system"
  SERVER_PORT: "9090"
  VITE_API_BASE_URL: "http://localhost:9090"
